fluentd-base: Dockerfile
Signed-off-by: Wang Chongyang <15757101689@163.com>

ERROR:  Error installing async:
The last version of console (~> 1.10) to support your Ruby & RubyGems
was 1.1nconsole requires Ruby version >= 2.7. The current ruby version
is 2.6.8.205.