container/add-software: add enable centos yum repo to fix build fails
[error]
root@taishan200-2280-2s64p-128g--a1002 /c/compass-ci/container/add-software# ./build
Sending build context to Docker daemon   5.12kB
Step 1/3 : FROM centos:8
 ---> e6a0117ec169
Step 2/3 : MAINTAINER Xu Xijian <hdxuxijian@163.com>
 ---> Using cache
 ---> 5453d4402617
Step 3/3 : RUN yum install -y rsync
 ---> Running in ea497a75c1ec
CentOS Linux 8 - AppStream                       16  B/s |  38  B     00:02
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c yum install -y rsync' returned a non-zero code: 1

container/fetch-mail also have same issue, and no need to update
package, so remove yum update -y.

base image of container/fetch-mail, specify the version is more stable,
so use centos:8.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>