container/webhook: fix failed to build images
[error]
ERROR:  Error installing bunny:
        ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/2.6.0/gems/rbtree-0.4.4
/usr/bin/ruby -I /usr/lib/ruby/2.6.0 -r ./siteconf20211220-1-3b3y6m.rb extconf.rb
checking for rb_exec_recursive() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --enable-debug
        --disable-debug
/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

[how]
when use gem install bunny, you have to install development tools(make gcc g++) first.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>