git_mirror.rb: fix that some repo files will cause a nil error
[errmsg]
git-mirror: /c/compass-ci/lib/git_mirror.rb:36:in `get_url': undefined method `include?' for nil:NilClass (NoMethodError)

[file info]
----
-url: []

Signed-off-by: Li Yuanchao <lyc163mail@163.com>