lib/matrix.rb: fix NoMethodError
[Why]
/home/wangyong/compass-ci/lib/matrix2.rb:21:in `set_pre_value': undefined method `sum' for 1:Integer (NoMethodError)
Did you mean?  succ
root cause:
	if a job has *.yaml(except job.yaml) in result_root, will meet this error
	when merge it to stats.json directly.

[How]
remove the logical handle *.yaml from lib/matrix.rb at first,
we should only handle $script.yaml, and the feature will be done in
other patch

Signed-off-by: Lu Weitao <luweitaobe@163.com>