lib/compare.rb: fix NoMethodError
Traceback (most recent call last):
        3: from ./t:85:in `<main>'
        2: from /home/lwt/compass-ci/lib/compare.rb:258:in `combine_compare_dims'
        1: from /home/lwt/compass-ci/lib/compare.rb:258:in `each'
/home/lwt/compass-ci/lib/compare.rb:260:in `block in combine_compare_dims': undefined method `each_value' for "group_id":String (NoMethodError)

[root cause]
there is a scenario:
  series like: ["group_id"]
  max_series_num: 3

  we need get 3 series by auto group jobs that query ES by filter
  when jobs is empty, series also is empty
  we should return empty compare result
  but actually, we parse request_body['series']
  so cause this error

Signed-off-by: Lu Weitao <luweitaobe@163.com>