lib/compare.rb fix NoMethodError
original error:
  /home/lwt/work/crystal-ci/lib/compare_matrixes.rb:385:in `compare_group_matrices':
  undefined method `each' for nil:NilClass (NoMethodError)
cause analysis:
  in auto group mode, group_matrices may be nil with user's comparison conditions

Signed-off-by: Lu Weitao <luweitaobe@163.com>