sparrow/0-package: use stable version to fix failed to gem install error
[error]
ERROR:  Error installing activesupport:
	activesupport requires Ruby version >= 2.7.0. The current ruby
	version is 2.5.0.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>