lib/env.cr: rename to web_env.cr
[Why]
env.cr is the same as the file name provided by the crystal.

[Error]
/c/cci/scheduler $ crystal a.cr
Showing last frame. Use --error-trace for full trace.
In /usr/lib/crystal/core/json/from_json.cr:140:5
  140 | def Set.new(pull : JSON::PullParser)
Error: undefined constant Set

Signed-off-by: Wu Zhende <wuzhende666@163.com>