lib/json_logger: fix initializate without env
[Error]
In lib/json_logger.cr:9:61
 9 | def initialize(logdev = STDOUT, formatter = my_formatter, @env = nil)
Error: instance variable @env of JSONLogger was inferred to be Nil, but Nil alone provides no information

This error is reported when "JSONLogger.new" is used.
Fix it.

Signed-off-by: Wu Zhende <wuzhende666@163.com>