sparrow/0-package/common: fix failed to gem install bunny
[error]
when run a multi-qemu.yaml job, the error message as follows:
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (http://api.rubygems.org/quick/Marshal.4.8/activesupport-6.1.3.2.gemspec.rz)

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bunny (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /c/compass-ci/lib/mq_client.rb:5:in `<top (required)>'
        from /c/compass-ci/providers/multi-qemu:10:in `require_relative'
        from /c/compass-ci/providers/multi-qemu:10:in `<main>'

Signed-off-by: Liu Yinsi <liuyinsi@163.com>