container: manjaro: fix dependency issues
pacman -Sy cause dependency issues, must use pacman -Syu.

When build manjaro, error message as follows:

	util-linux-libs and libutil-linux are in conflict. Remove libutil-linux? [y/N]
	util-linux-libs and libutil-linux are in conflict
	error: unresolvable package conflicts detected
	error: failed to prepare transaction (conflicting dependencies)

See https://wiki.archlinux.org/index.php/Pacman

Signed-off-by: Liu Yinsi <liuyinsi@163.com>