sparrow: fix logging-es run error
1. configure user and group to fix error message as follows:

Likely root cause: java.nio.file.AccessDeniedException:
/srv/es/logging-es/nodes

2. configure vm.max_map_count=262144 to fix error message as follows:

ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low,
increase to at least [262144]

3. "sysctl -p" make sysctl.conf to take effect.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>