container/*: add gem version activesupport:6.1.4.4 to fix gem install error
before: gem install activesupport
after:  gem install activesupport:6.1.4.4

[error]
ERROR:  Error installing activesupport:
        The last version of activesupport (>= 0) to support your Ruby & RubyGems was 6.1.4.4. Try installing it with `gem install activesupport -v 6.1.4.4`
	 activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.6.8.205.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>