container: fix failed to build archlinux images in x86_64 machine
[why]
when build archlinux images in x86_64 machine
error: failed retrieving file 'community.db' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'community.db' from mirrors.163.com : The requested URL returned error: 404
error: failed retrieving file 'community.db' from mirror.archlinuxarm.org : The requested URL returned error:404
error: failed to update community (failed to retrieve some files)
error: failed to synchronize all databases
The command '/bin/sh -c pacman --needed --noprogressbar --noconfirm  -Syu &&
pacman --needed --noprogressbar --noconfirm  -S bash zsh git openssh rsync make gcc
tzdata sudo coreutils util-linux vim gawk' returned a non-zero code: 1

because archlinux mirrorlist not support x86_64 machine.

[how]
1. add 2 folder root/aarch64/etc/pacman.d/mirrorlist and root/x86_64/etc/pacman.d/mirrorlist;
In addition, 'COPY' in Dockerfile, the directory itself is not copied, only its contents.
Please see: https://docs.docker.com/engine/reference/builder/#copy
2. use $(arch) to choose mirrorlist according to different system architecture.

Signed-off-by: Liu Yinsi <liuyinsi@163.com>