fix: scheduler: 1 bug fix and uuid simple check
job.update(hash) direct operate to input hash, this make caller into
error condition.
<<<
Should not direct update id, use update_id, ignore this
Exception: Nil assertion failed (NilAssertionError)
...
  from /c/cci/src/lib/sched.cr:0:25 in 'update_job_parameter'
>>>

simply check the uuid exists (if job's SCHED_HOST is different to
scheduler's SCHED_HOST).

at intranet, we may have many ip, that scheduler binds. and we may start different
  scheduler, bind to different ip. but they all scheduer send job to same taskqueue.
  so this "job's SCHED_HOST" != "scheduler's SCHED_HOST" *does not a good rule*.
  current we use this rule.

Signed-off-by: Tong Qunfeng <taxcom@tom.com>