container/fluentd-base: fix failed to build image
[error]
ERROR:  Error installing async:
        There are no versions of io-event (~> 1.0.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
        io-event requires Ruby version >= 3.0. The current ruby version is 2.5.0.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>