scheduler: remove redis dependency
wfg@crystal ~/compass-ci/src% make

In scheduler/redis_client.cr:6:1

 6 | require "redis/cluster"
      ^
      Error: can't find file 'redis/cluster'

      If you're trying to require a shard:
      - Did you remember to run `shards install`?

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>