container/fluentd-base: fix failed to build image
When execute fluentd-base/build, error message as follows:
ERROR:  Could not find a valid gem 'fluent-plugin-elasticsearch' (=7.11.1)
(required by 'fluent-plugin-elasticsearch' (7.11.1)) in any repository
ERROR:  Possible alternatives: fluent-plugin-elasticsearch

Because fluent-plugin-elasticsearch is ok, no need to specify version.

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>