sparrow: fix os-nfs run error
run container os-nfs failed.
1.use "--mount" to fix error message as follows:

exportfs: /exports does not support NFS export
ERROR: /usr/sbin/exportfs failed

2.add "fsid=1,fsid=2..." to fix error message as follows:

exportfs: /exports/result requires fsid= for NFS export
exportfs: /exports/initrd requires fsid= for NFS export
exportfs: /exports/osimage requires fsid= for NFS export
exportfs: /exports/os-rw requires fsid= for NFS export
exportfs: /exports/os requires fsid= for NFS export

Signed-off-by: Liu Yinsi <liuyinsi@huawei.com>