git_mirror: fix that README.md in upstream-repos cause a load error
[why]
As README.md or other docs in upstream-repos, and they are not yaml
file. But git-mirror load all files in upstream-repos as yaml file, so
there comes out a load error.

Now files whose dirname is 'xxx/upstream-repos' will not be loaded.

[errmsg]
...in `load_repo_file': undefined method `[]=' for x:Integer (NoMethodError)

Signed-off-by: Li Yuanchao <lyc163mail@163.com>