answerback-email: fix bugs and optimize
1. set default option '-h'
[why]
the tool will show help message if no option specified
the tool will get no email address without both '-e' and '-f'

[how]
add '-h' as default option if no option specified
options will be reset to '-h' if both '-e' and '-f' are not specified

2. fix undefined method 'empty'
[why]
the original value is defined 'nil' for my_email
when execute answerback-email with no '-e' or '-f', it will throw error as:
raceback (most recent call last):
        2: from ./answerback-email.rb:213:in `<main>'
        1: from ./answerback-email.rb:184:in `send_account'
./answerback-email.rb:155:in `check_my_email': undefined method `empty?' for nil:NilClass (NoMethodError)

[how]
use '.nil?' instead of '.empty?'

3. option parse error
[why]
if add no required value for option, the option will use the field that follows as its value.
example:
./answerback-email.rb -e -n name
Not a standard format email: -n.

[how]
add value check for options that need a value

Signed-off-by: Luan Shengde <shdluan@163.com>