qcow2rootfs: change yum source to fix build timeout error
[Error Msg]
Step 4/7 : RUN yum makecache &&     yum install -y --skip-broken libvirt libguestfs-tools xz expect openssl &&     yum clean all
 ---> Running in c443a95dbd5f
CentOS-8 - AppStream2.2 kB/s | 2.5 MB     19:23
Errors during downloading metadata for repository 'AppStream':
  - Curl error (28): Timeout was reached for http://mirror.centos.org/centos/8/AppStream/aarch64/os/repodata/ce3501f14219e71c21c1e40c6f91ba41bd37b59345c5a7dd6d680ef4b279b95a-filelists.xml.gz [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
  - Curl error (28): Timeout was reached for http://mirror.centos.org/centos/8/AppStream/aarch64/os/repodata/cc0e75f5237c3f5ddfea6ab0de1056df5bb8bbf1273b5ecb907ed7c1c72897f3-primary.xml.gz [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
  - Curl error (18): Transferred a partial file for http://mirror.centos.org/centos/8/AppStream/aarch64/os/repodata/ce3501f14219e71c21c1e40c6f91ba41bd37b59345c5a7dd6d680ef4b279b95a-filelists.xml.gz [transfer closed with 1750223 bytes remaining to read]
Error: Failed to download metadata for repo 'AppStream': Yum repo downloading error: Downloading error(s):
  repodata/cc0e75f5237c3f5ddfea6ab0de1056df5bb8bbf1273b5ecb907ed7c1c72897f3-primary.xml.gz - Cannot download, all mirrors were already tried without success;
  repodata/ce3501f14219e71c21c1e40c6f91ba41bd37b59345c5a7dd6d680ef4b279b95a-filelists.xml.gz - Cannot download, all mirrors were already tried without success

Signed-off-by: Yu Chuan <13186087857@163.com>