container/defconfig.rb: fix undefined method `includes' for nil:NilClass
[Why]
When "ENV['action']" is nil, it will output error in this line in defconfig.rb:
return unless ENV['action'].include? 'run-only'

[errlog]
Traceback (most recent call last):
        1: from ./build:15:in `<main>'
/home/xxj/compass-ci/container/defconfig.rb:52:in `docker_skip_rebuild': undefined method `include?' for nil:NilClass (NoMethodError)

Signed-off-by: Xu Xijian <hdxuxijian@163.com>