sparrow/install-client: exit if not found lockfile-create command
[error]
==> /tmp/stderr <==
--2021-07-14 18:11:29--  http://abf-downloads.openmandriva.org/rock/repository/aarch64/main/release/lib64lockfile1-1.16-1-omv4002.aarch64.rpm
Resolving abf-downloads.openmandriva.org (abf-downloads.openmandriva.org)... failed: Name or service not known.
wget: unable to resolve host address ‘abf-downloads.openmandriva.org’
error: open of lib64lockfile1-1.16-1-omv4002.aarch64.rpm failed: No such file or directory

If failed to download lockfile rpm because unstable network, jobs for multi-qemu-docker.yaml must will be failed,
this command will be used in $CCI_SRC/providers/qemu.sh, so use check_cmd() to add prompt information. It's easy to locate the problem.

Signed-off-by: Liu Yinsi <liuyinsi@163.com>